export const currencyDetails: Record<string, { symbol: string; code: string }> = {
  "Afghan Afghani": { symbol: "؋", code: "AFN" },
  "Albanian Lek": { symbol: "L", code: "ALL" },
  "Algerian Dinar": { symbol: "د.ج", code: "DZD" },
  "Euro": { symbol: "€", code: "EUR" },
  "Angolan Kwanza": { symbol: "Kz", code: "AOA" },
  "East Caribbean Dollar": { symbol: "$", code: "XCD" },
  "Argentine Peso": { symbol: "$", code: "ARS" },
  "Armenian Dram": { symbol: "֏", code: "AMD" },
  "Australian Dollar": { symbol: "$", code: "AUD" },
  "Azerbaijani Manat": { symbol: "₼", code: "AZN" },
  "Bahamian Dollar": { symbol: "$", code: "BSD" },
  "Bahraini Dinar": { symbol: ".د.ب", code: "BHD" },
  "Bangladeshi Taka": { symbol: "৳", code: "BDT" },
  "Barbadian Dollar": { symbol: "$", code: "BBD" },
  "Belarusian Ruble": { symbol: "Br", code: "BYN" },
  "Belize Dollar": { symbol: "$", code: "BZD" },
  "West African CFA franc": { symbol: "Fr", code: "XOF" },
  "Bhutanese Ngultrum": { symbol: "Nu.", code: "BTN" },
  "Bolivian Boliviano": { symbol: "Bs.", code: "BOB" },
  "Bosnia and Herzegovina convertible mark": { symbol: "KM", code: "BAM" },
  "Botswana Pula": { symbol: "P", code: "BWP" },
  "Brazilian Real": { symbol: "R$", code: "BRL" },
  "Brunei Dollar": { symbol: "$", code: "BND" },
  "Bulgarian Lev": { symbol: "лв", code: "BGN" },
  "Burundian Franc": { symbol: "Fr", code: "BIF" },
  "Cape Verdean Escudo": { symbol: "Esc", code: "CVE" },
  "Cambodian Riel": { symbol: "៛", code: "KHR" },
  "Central African CFA franc": { symbol: "Fr", code: "XAF" },
  "Canadian Dollar": { symbol: "$", code: "CAD" },
  "Chilean Peso": { symbol: "$", code: "CLP" },
  "Renminbi": { symbol: "¥", code: "CNY" },
  "Colombian Peso": { symbol: "$", code: "COP" },
  "Comorian Franc": { symbol: "Fr", code: "KMF" },
  "Costa Rican Colón": { symbol: "₡", code: "CRC" },
  "Cuban Peso": { symbol: "$", code: "CUP" },
  "Czech Koruna": { symbol: "Kč", code: "CZK" },
  "Danish Krone": { symbol: "kr", code: "DKK" },
  "Djiboutian Franc": { symbol: "Fr", code: "DJF" },
  "Dominican Peso": { symbol: "$", code: "DOP" },
  "Congolese Franc": { symbol: "Fr", code: "CDF" },
  "United States Dollar": { symbol: "$", code: "USD" },
  "Egyptian Pound": { symbol: "£", code: "EGP" },
  "Eritrean Nakfa": { symbol: "Nfk", code: "ERN" },
  "Swazi Lilangeni": { symbol: "L", code: "SZL" },
  "Ethiopian Birr": { symbol: "Br", code: "ETB" },
  "Fijian Dollar": { symbol: "$", code: "FJD" },
  "Gambian Dalasi": { symbol: "D", code: "GMD" },
  "Georgian Lari": { symbol: "₾", code: "GEL" },
  "Ghanaian Cedi": { symbol: "₵", code: "GHS" },
  "Guatemalan Quetzal": { symbol: "Q", code: "GTQ" },
  "Guinean Franc": { symbol: "Fr", code: "GNF" },
  "Guyanese Dollar": { symbol: "$", code: "GYD" },
  "Haitian Gourde": { symbol: "G", code: "HTG" },
  "Honduran Lempira": { symbol: "L", code: "HNL" },
  "Hungarian Forint": { symbol: "Ft", code: "HUF" },
  "Icelandic Króna": { symbol: "kr", code: "ISK" },
  "Indian Rupee": { symbol: "₹", code: "INR" },
  "Indonesian Rupiah": { symbol: "Rp", code: "IDR" },
  "Iranian Rial": { symbol: "﷼", code: "IRR" },
  "Iraqi Dinar": { symbol: "ع.د", code: "IQD" },
  "Israeli New Shekel": { symbol: "₪", code: "ILS" },
  "Jamaican Dollar": { symbol: "$", code: "JMD" },
  "Japanese Yen": { symbol: "¥", code: "JPY" },
  "Jordanian Dinar": { symbol: "د.ا", code: "JOD" },
  "Kazakhstani Tenge": { symbol: "₸", code: "KZT" },
  "Kenyan Shilling": { symbol: "Sh", code: "KES" },
  "Kuwaiti Dinar": { symbol: "د.ك", code: "KWD" },
  "Kyrgyzstani Som": { symbol: "с", code: "KGS" },
  "Lao Kip": { symbol: "₭", code: "LAK" },
  "Lebanese Pound": { symbol: "ل.ل", code: "LBP" },
  "Lesotho Loti": { symbol: "L", code: "LSL" },
  "Liberian Dollar": { symbol: "$", code: "LRD" },
  "Libyan Dinar": { symbol: "ل.د", code: "LYD" },
  "Swiss Franc": { symbol: "Fr", code: "CHF" },
  "Malagasy Ariary": { symbol: "Ar", code: "MGA" },
  "Malawian Kwacha": { symbol: "MK", code: "MWK" },
  "Malaysian Ringgit": { symbol: "RM", code: "MYR" },
  "Maldivian Rufiyaa": { symbol: "Rf", code: "MVR" },
  "Mauritanian Ouguiya": { symbol: "UM", code: "MRU" },
  "Mauritian Rupee": { symbol: "₨", code: "MUR" },
  "Mexican Peso": { symbol: "$", code: "MXN" },
  "Moldovan Leu": { symbol: "L", code: "MDL" },
  "Mongolian Tögrög": { symbol: "₮", code: "MNT" },
  "Moroccan Dirham": { symbol: "د.م.", code: "MAD" },
  "Mozambican Metical": { symbol: "MT", code: "MZN" },
  "Burmese Kyat": { symbol: "Ks", code: "MMK" },
  "Namibian Dollar": { symbol: "$", code: "NAD" },
  "Nepalese Rupee": { symbol: "₨", code: "NPR" },
  "New Zealand Dollar": { symbol: "$", code: "NZD" },
  "Nicaraguan Córdoba": { symbol: "C$", code: "NIO" },
  "Nigerian Naira": { symbol: "₦", code: "NGN" },
  "North Korean Won": { symbol: "₩", code: "KPW" },
  "Macedonian Denar": { symbol: "ден", code: "MKD" },
  "Norwegian Krone": { symbol: "kr", code: "NOK" },
  "Omani Rial": { symbol: "ر.ع.", code: "OMR" },
  "Pakistani Rupee": { symbol: "₨", code: "PKR" },
  "Panamanian Balboa": { symbol: "B/.", code: "PAB" },
  "Papua New Guinean Kina": { symbol: "K", code: "PGK" },
  "Paraguayan Guaraní": { symbol: "₲", code: "PYG" },
  "Peruvian Sol": { symbol: "S/.", code: "PEN" },
  "Philippine Peso": { symbol: "₱", code: "PHP" },
  "Polish Złoty": { symbol: "zł", code: "PLN" },
  "Qatari Riyal": { symbol: "ر.ق", code: "QAR" },
  "Romanian Leu": { symbol: "lei", code: "RON" },
  "Russian Ruble": { symbol: "₽", code: "RUB" },
  "Rwandan Franc": { symbol: "Fr", code: "RWF" },
  "Samoan Tālā": { symbol: "T", code: "WST" },
  "São Tomé and Príncipe Dobra": { symbol: "Db", code: "STN" },
  "Saudi Riyal": { symbol: "ر.س", code: "SAR" },
  "Serbian Dinar": { symbol: "дин.", code: "RSD" },
  "Seychellois Rupee": { symbol: "₨", code: "SCR" },
  "Sierra Leonean Leone": { symbol: "Le", code: "SLL" },
  "Singapore Dollar": { symbol: "$", code: "SGD" },
  "Solomon Islands Dollar": { symbol: "$", code: "SBD" },
  "Somali Shilling": { symbol: "Sh", code: "SOS" },
  "South African Rand": { symbol: "R", code: "ZAR" },
  "South Korean Won": { symbol: "₩", code: "KRW" },
  "South Sudanese Pound": { symbol: "£", code: "SSP" },
  "Sri Lankan Rupee": { symbol: "Rs", code: "LKR" },
  "Sudanese Pound": { symbol: "ج.س.", code: "SDG" },
  "Surinamese Dollar": { symbol: "$", code: "SRD" },
  "Swedish Krona": { symbol: "kr", code: "SEK" },
  "Syrian Pound": { symbol: "£", code: "SYP" },
  "New Taiwan Dollar": { symbol: "$", code: "TWD" },
  "Tajikistani Somoni": { symbol: "SM", code: "TJS" },
  "Tanzanian Shilling": { symbol: "Sh", code: "TZS" },
  "Thai Baht": { symbol: "฿", code: "THB" },
  "Tongan Paʻanga": { symbol: "T$", code: "TOP" },
  "Trinidad and Tobago Dollar": { symbol: "$", code: "TTD" },
  "Tunisian Dinar": { symbol: "د.ت", code: "TND" },
  "Turkish Lira": { symbol: "₺", code: "TRY" },
  "Turkmenistan Manat": { symbol: "m", code: "TMT" },
  "Ugandan Shilling": { symbol: "Sh", code: "UGX" },
  "Ukrainian Hryvnia": { symbol: "₴", code: "UAH" },
  "United Arab Emirates Dirham": { symbol: "د.إ", code: "AED" },
  "Pound Sterling": { symbol: "£", code: "GBP" },
  "Uruguayan Peso": { symbol: "$", code: "UYU" },
  "Uzbekistani Som": { symbol: "с", code: "UZS" },
  "Vanuatu Vatu": { symbol: "Vt", code: "VUV" },
  "Venezuelan Bolívar": { symbol: "Bs.S", code: "VES" },
  "Vietnamese Đồng": { symbol: "₫", code: "VND" },
  "Yemeni Rial": { symbol: "﷼", code: "YER" },
  "Zambian Kwacha": { symbol: "ZK", code: "ZMW" }
};
